### ISSUE TITLE
Synth smoking dataset not downloading correctly

### ISSUE THREAD

**Issue by waveswinger34** [bquistorff/synth_runner#22] opened 2018-07-24 11:27 UTC
# Smoking dataset is not the correct dataset
I type the following into Stata, version 15:
ssc install synth, replace all

then I type
sysuse smoking

Instead of a dataset for 39 US States for the years 1970-2000, I get a dataset from the following: (Smoking data from Lu & Ades (2006))

It is the wrong dataset. I have tried this on another computer and it is the same problem.  I'm running Windows 10. I can't find the correct dataset online anywhere.

Thanks very much,
Slawa Rokicki

**Comment by bquistorff** [comment] 2018-07-24 15:00
Duplicate of #20. You can download it from my repo [here](https://github.com/bquistorff/synth_runner/raw/master/code/ado/smoking.dta). I'll touch up the examples so to make this clear.

**Closed by bquistorff** 2018-07-24 15:00 UTC
Labels: duplicate
